// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Redpeper.Data;

namespace Redpeper.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191012222553_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Redpeper.Model.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("idPersona");

                    b.Property<int?>("personaId");

                    b.HasKey("Id");

                    b.HasIndex("personaId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Redpeper.Model.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("idPersona");

                    b.Property<int?>("personaId");

                    b.HasKey("Id");

                    b.HasIndex("personaId");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("Redpeper.Model.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("CorreoElectronico")
                        .HasMaxLength(100);

                    b.Property<string>("Direccion")
                        .HasMaxLength(200);

                    b.Property<string>("Dui")
                        .HasMaxLength(10);

                    b.Property<DateTime>("FechaNacimiento");

                    b.Property<string>("Nit")
                        .HasMaxLength(17);

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<char>("Sexo");

                    b.Property<string>("Telefono")
                        .HasMaxLength(9);

                    b.HasKey("Id");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("Redpeper.Model.Cliente", b =>
                {
                    b.HasOne("Redpeper.Model.Persona", "persona")
                        .WithMany()
                        .HasForeignKey("personaId");
                });

            modelBuilder.Entity("Redpeper.Model.Empleado", b =>
                {
                    b.HasOne("Redpeper.Model.Persona", "persona")
                        .WithMany()
                        .HasForeignKey("personaId");
                });
#pragma warning restore 612, 618
        }
    }
}
